package com.database.UserInfo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/user") // This means URL's start with /user (after Application path)
public class UserInfoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestParam String email, @RequestParam String name, @RequestParam String pw) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        UserInfo n = new UserInfo();
        n.setUserName(name);
        n.setEmail(email);
        n.setPW(pw);
        userRepository.save(n);
        return "Saved New User";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<UserInfo> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
