package com.database.LastRecipe;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Collections;
import java.util.Optional;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/last") // This means URL's start with /user (after Application path)
public class LastRecipeController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LastRecipeRepository lastRecipeRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestParam String email, @RequestParam String lastQuery) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Optional<LastRecipe> resultFromDB = lastRecipeRepository.findById(email);
        if (resultFromDB.isPresent()) {
            return "Query already exists";
        }

        LastRecipe lastRecipe = new LastRecipe(email, lastQuery);
        lastRecipeRepository.save(lastRecipe);
        return "Saved New Query";
    }

    @PostMapping(path = "/update") // Map ONLY POST Requests
    public @ResponseBody
    String updateUserInfo(@RequestParam String email, @RequestParam String lastQuery) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Optional<LastRecipe> resultFromDB = lastRecipeRepository.findById(email);
        if (!resultFromDB.isPresent()) {
            return "Query does not exist";
        }

        LastRecipe lastRecipe = resultFromDB.get();
        lastRecipe.setLastQuery(lastQuery);
        lastRecipeRepository.save(lastRecipe);
        return "Update the info for User";
    }

    @GetMapping(path = "/search")
    public @ResponseBody
    Iterable<LastRecipe> getUsers(@RequestParam String email) {
        // This returns a JSON or XML with the users

        Optional<LastRecipe> lastRecipe = lastRecipeRepository.findById(email);
        return lastRecipe.map(Collections::singleton)
                .orElseGet(Collections::emptySet);
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<LastRecipe> getAllUsers() {
        // This returns a JSON or XML with the users
        return lastRecipeRepository.findAll();
    }
}
