package com.database.DietRestriction;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/diet") // This means URL's start with /diet(after Application path)
public class DietResController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DietRestrictionRepo dietRestrictionRepo;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addDietRestriction(@RequestParam String diet, @RequestParam String exIngred, @RequestParam String intolerance) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        DietRestriction dietRestriction = new DietRestriction();
        dietRestriction.setDiet(diet);
        dietRestriction.setExingred(exIngred);
        dietRestriction.setIntolerance(intolerance);
        return "Saved New Dietary Restriction";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<DietRestriction> getAllDietRestrictions() {
        // This returns a JSON or XML with the users
        return dietRestrictionRepo.findAll();
    }
}
